### ISSUE TITLE
run on babashka

### ISSUE THREAD

**Issue by henryw374** [henryw374/cljc.java-time#10]
babashka doesnt support the dot special form atm, so probably some reader conditionals would be required https://github.com/borkdude/babashka#reader-conditionals

**Comment by borkdude** [comment]
@henryw374 What dot special form doesn't work in babashka? Do you have an example? Maybe this should be fixed in babashka / sci?

**Comment by henryw374** [comment]
ah, sorry, I saw this issue https://github.com/borkdude/babashka/issues/199. I see it is closed now.

for example, this field access doesn't work in babashka

`(def max (. java.time.LocalDate -MAX))`

but does in clojure and clojurescript. FYI The minus sign in  `-MAX` is necessary for cljs, but happens to work in clojure as well.

this does work in bb: `java.time.LocalDate/MAX`

**Comment by borkdude** [comment]
I've made an issue here: https://github.com/borkdude/sci/issues/339
For now I would recommend using a reader conditional and use the preferred form of `Class/field` in the `:clj` branch.

**Comment by henryw374** [comment]
cheers

**Comment by henryw374** [comment]
fixed in e3d184b by adding extra reader conditionals :)

**Comment by borkdude** [comment]
Confirmed!

<img width="564" alt="Screenshot 2020-05-29 19 47 34" src="https://user-images.githubusercontent.com/284934/83289402-4aa2fe00-a1e5-11ea-96da-644806aa4e69.png">

**Comment by borkdude** [comment]
@henryw374 I decided to run the tests for this library with babashka and found a few classes that were still missing. I added those:

https://github.com/borkdude/babashka/commit/696d4102a7c347bf57902ee84fa2f2665bf4574a

Should be part of the 0.1.0 release coming up soon.

**Comment by henryw374** [comment]
Great!
